{
 "title": "Pipeline Service",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "PipelineRuns Per Hour",
   "type": "graph",
   "description": "Completed PipelineRuns per hour",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (rate(tekton_pipelines_controller_pipelinerun_count[1h]))* 3600"
    }
   ]
  },
  {
   "title": "PipelineRun Success",
   "type": "stat",
   "description": "PipelineRun success per hour",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate(tekton_pipelines_controller_pipelinerun_count{status=\"success\"}[1h])) / sum (rate(tekton_pipelines_controller_pipelinerun_count[1h]))"
    }
   ]
  },
  {
   "title": "TaskRuns Per Hour",
   "type": "graph",
   "description": "Completed TaskRuns Per Hour",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (rate(tekton_pipelines_controller_taskrun_count[1h]))* 3600"
    }
   ]
  },
  {
   "title": "TaskRun Success",
   "type": "stat",
   "description": "TaskRun success per hour",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate(tekton_pipelines_controller_taskrun_count{status=\"success\"}[1h])) / sum (rate(tekton_pipelines_controller_taskrun_count[1h]))"
    }
   ]
  },
  {
   "title": "Pipelines-Controller Resource Utlization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "repeat": "datasource"
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "Total average CPU usage of the Pipelines over the past hour.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"tekton-pipelines-controller-.*\"}[5m]))"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "graph",
   "description": "Working set memory usage of Pipelines Controller Containers ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\"tekton-pipelines-controller-.*\"})"
    }
   ]
  },
  {
   "title": "Pipelines Controller Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "repeat": "datasource"
  },
  {
   "title": "Pipelineruns Running",
   "type": "stat",
   "description": "Number of Pipelineruns executing currently",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tekton_pipelines_controller_running_pipelineruns_count{prometheus=\"openshift-user-workload-monitoring/user-workload\"}"
    }
   ]
  },
  {
   "title": "Taskruns Running",
   "type": "stat",
   "description": "Number of Taskruns executing currently",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tekton_pipelines_controller_running_taskruns_count{prometheus=\"openshift-user-workload-monitoring/user-workload\"}"
    }
   ]
  },
  {
   "title": "Pipelines Controller Container Restarts",
   "type": "graph",
   "description": "Frequency of Pipelines Controller restarts (This is experimental and may be removed in future)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kube_pod_container_status_restarts_total{namespace=\"openshift-pipelines\", pod=~\"tekton-pipelines-controller-.*\"}[7d])"
    }
   ]
  },
  {
   "title": "Workqueue Depth",
   "type": "timeseries",
   "description": "The workqueue for the Tekton Pipelines Reconcilers",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(tekton_pipelines_controller_workqueue_depth)"
    }
   ]
  },
  {
   "title": "Pipelines Client Results",
   "type": "timeseries",
   "description": "Total number of Kubernetes API requests by Tekton Controller",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(tekton_pipelines_controller_client_results{prometheus=\"openshift-user-workload-monitoring/user-workload\"}[1h])*3600"
    }
   ]
  },
  {
   "title": "Taskruns Pod Latency",
   "type": "timeseries",
   "description": "Scheduling latency for the Taskruns pods",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(tekton_pipelines_controller_taskruns_pod_latency)"
    }
   ]
  }
 ]
}